### ISSUE TITLE
CC validation fails on amex

### ISSUE THREAD

**Issue by stephenhandley** [hsnayd/validetta#41]
Amex has 15 digits. 

See test examples here:
https://stripe.com/docs/testing

**Comment by hsnayd** [comment]
Hİ @stephenhandley 

Validetta does not have advanced credit card validation. For more complicated credit cart validation, I recommend using external plugins. You can use [jquery-creditcardvalidator](https://github.com/PawelDecowski/jquery-creditcardvalidator) plugin.

Here is an example about how to validetta and jquery-creditcardvalidator work together.
http://jsfiddle.net/tf3cLd5b/5/

Thank you.

**Comment by stephenhandley** [comment]
In appreciate the suggestion but still don't really understand why you claim to do credit card validation unless you do so properly. It wouldnt characterize it as not "advanced", I would characterize it as "doesn't work for all credit cards and so is essentially useless". yr documentation does nothing to inform the user of the fact that it fails to cover common use cases. you should probably either do it properly or remove it.

**Comment by hsnayd** [comment]
Yes you are right but I didn't know Its not working on amex type credit card until you told. I was already planning on removing it, because It can be done with callback method by externally. Credit card validation is a complex work and should not be in core. Because most people are not using it. It could add externally as an example by using callback method in the next version.

Btw, Validetta still developing in develop branch, and there are many improve completed. I will add a warning to credit cart validation method related with this situation. 

Thank you.

**Comment by stephenhandley** [comment]
sounds good tahnks
